name: deploy
description: Deploy python greetings

inputs:
  repo-path:
    required: true
    description: Directory for python greetings
  environment:
    required: true
    description: Environment
  port:
    required: true
    description: Port number

runs:
  using: composite
  steps:
    - name: Python greetings repository
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: ${{ inputs.repo-path }}

    - name: Install pm2 dependency
      shell: cmd
      working-directory: ${{ inputs.repo-path }}
      run: |
        echo Installing pm2 dependency..
        npm install pm2

    - name: Delete old connection
      shell: cmd
      working-directory: ${{ inputs.repo-path }}
      run: |
        echo Deleting old connection..
        node_modules\.bin\pm2 delete greetings-app-${{ inputs.environment }} || exit 0

    - name: Start new connection
      shell: cmd
      run: |
        echo Starting new connection..
        dir
        node_modules\.bin\pm2 start -n greetings-app-${{ inputs.environment }} ${{ inputs.repo-path }}/app.py --interpreter venv\Scripts\pythonw.exe -- --port ${{ inputs.port }}
