name: python-greetings

on:
  push:
    branches: ["main"]
    paths-ignore: 
      - 'README.md'
      - 'Jenkinsfile'
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build
        with:
          repo-path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environment: "dev"
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environment: "dev"

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environment: "stg"
          port: 7002
  
  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environment: "stg"
  
  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environment: "preprod"
          port: 7003
  
  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environment: "preprod"
    
  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environment: "prod"
          port: 7004
  
  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environment: "prod"
