name: python greetings

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    name: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Install Python dependencies
        uses: ./.github/actions/build
        with:
          repo-path: python-greetings

  deploy-to-dev:
    name: deploy-to-dev
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Deploy to dev
        uses: ./.github/actions/deploy
        with:
          environment: dev
          port: '7001'
          repo-path: python-greetings

  tests-on-dev:
    name: tests-on-dev
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Run tests on dev
        uses: ./.github/actions/test
        with:
          environment: dev
          repo-path: course-js-api-framework

  deploy-to-stg:
    name: deploy-to-stg
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Deploy to stg
        uses: ./.github/actions/deploy
        with:
          environment: stg
          port: '7002'
          repo-path: python-greetings

  tests-on-stg:
    name: tests-on-stg
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Run tests on stg
        uses: ./.github/actions/test
        with:
          environment: stg
          repo-path: course-js-api-framework

  deploy-to-preprod:
    name: deploy-to-preprod
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Deploy to preprod
        uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: '7003'
          repo-path: python-greetings

  tests-on-preprod:
    name: tests-on-preprod
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Run tests on preprod
        uses: ./.github/actions/test
        with:
          environment: preprod
          repo-path: course-js-api-framework

  deploy-to-prod:
    name: deploy-to-prod
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Deploy to prod
        uses: ./.github/actions/deploy
        with:
          environment: prod
          port: '7004'
          repo-path: python-greetings

  tests-on-prod:
    name: tests-on-prod
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6

      - name: Run tests on prod
        uses: ./.github/actions/test
        with:
          environment: prod
          repo-path: course-js-api-framework
